### ISSUE TITLE
Prints

### ISSUE THREAD

**Issue by missingdays** [rthornton128/calc#23]
A calculated value prints without \n in the end, so it makes reading output of the program harder.

**Comment by rthornton128** [comment]
This issue is fixed in master and the Calc2 release. I will consider back-porting it.

You can fix this yourself locally by changing the C printf on line 84 of comp/comp.go to include "\\n" to look like this:
fmt.Fprintf(c.fp, "printf(\"%%d\\n\", %d);\n", c.compNode(f.Root))

**Comment by missingdays** [comment]
Yep, fixed it on my machine as soon as found it.
Glad to hear you fixed it!
